[build]
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = { Role = ["admin"] }

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true
  conditions = { Role = ["admin"] }

[[redirects]]
  from = "/admin"
  to = "/admin-unauthorized.html"
  status = 401
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin-unauthorized.html"
  status = 401
  force = true
